### ISSUE TITLE
ipv4 validate has error in some cases

### ISSUE THREAD

**Issue by light049** [whitequark/ipaddr.js#45] opened 2016-06-22 05:00 UTC
1. ipaddr.IPvX.isValid('5') 
2. ipaddr.IPvX.isValid('0000.0000.00000.00') 
3. ipaddr.IPvX.isValid('1.1.1.00200')')

All should be false

**Comment by whitequark** [comment] 2016-06-22 05:02
Duplicate of #44.

**Closed by whitequark** 2016-06-22 05:02 UTC

**Comment by whitequark** [comment] 2016-07-08 09:53
See `ipaddr.IPv4.isValidFourPartDecimal` in the 1.2.0 release.
