### ISSUE TITLE
isValid method throws error if undefined is passed in

### ISSUE THREAD

**Issue by EnzoMartin** [whitequark/ipaddr.js#33] opened 2015-12-09 14:12 UTC
No check on if string is defined (or is actually a string) is done before invoking `indexOf` which results in throwing an unhandled error instead of returning `false` as would be expected

```
ipaddr.IPv6.isValid = (string) ->
  # Since IPv6.isValid is always called first, this shortcut
  # provides a substantial performance gain.
  if string.indexOf(":") == -1
    return false
```

**Comment by whitequark** [comment] 2015-12-09 14:14
Duplicate of #32

**Comment by EnzoMartin** [comment] 2015-12-09 14:15
That PR is closed, and does not address the fact that the `isValid` function does not always return a boolean

**Comment by whitequark** [comment] 2015-12-09 14:15
The precondition for `isValid` is that the argument is a string. That was not always the case, and it was working with `undefined` by mere accident.

**Comment by EnzoMartin** [comment] 2015-12-09 14:16
That's the thing though, you can't be sure it's a string, and if the code is specifically tailored to only work with certain kinds of input (in this case a string or array), then it should always default to the fail case, which in this case would be `false`

**Comment by EnzoMartin** [comment] 2015-12-09 14:26
All it would take to fix it and make it bulletproof is check the type is a string.

```javascript
if typeof string === "string" && string.indexOf(":") == -1
```

Otherwise you're intentionally leaving a hole in your code that will generate unhandled exceptions for people if malformed data is passed in. Since there's no callback, there's no way to properly handle it from my code's perspective should unexpected data go in, even more so when it's part of another module

**Comment by whitequark** [comment] 2015-12-09 14:28
that doesn't handle String objects though.

**Comment by EnzoMartin** [comment] 2015-12-09 14:29
`indexOf` is only available on arrays or strings

**Comment by whitequark** [comment] 2015-12-09 14:30
> new String("x").indexOf
< indexOf() { [native code] }
> typeof new String("x")
> "object"

**Comment by whitequark** [comment] 2015-12-09 14:33
oh well, nevermind, that wouldn't break the check, just make it slightly slower.

**Closed** 2015-12-09 14:34 UTC

**Comment by EnzoMartin** [comment] 2015-12-09 14:44
Awesome!

Sorry to be a bit pedantic about this, but technically that check still isn't right as you should be checking that string is *not* a string then return false. That was my mistake in my original comment which I edited later but you probably missed it, apologies!

It passes your test now because it never does the 2nd check of `indexOf`, and then being catch in the try/catch, but it technicaly should be failing early by ensuring that any continuance of the function will only be done with string being a string

**Comment by whitequark** [comment] 2015-12-09 14:46
That was done deliberately. You can see that the logical operator is also reversed; this is to handle the case of passing a String object.

**Comment by EnzoMartin** [comment] 2015-12-09 14:47
Fair enough

**Comment by EnzoMartin** [comment] 2015-12-09 14:47
Thanks for fixing this :+1:
