### ISSUE TITLE
isValid() returns true on single digit value

### ISSUE THREAD

**Issue by dsuwirya** [whitequark/ipaddr.js#51] opened 2017-03-30 19:45 UTC
Hi,

isValid() currently returns true on:
- single digit value, like: 0, 1, 100, 1000, ...
- also on this one: 10.168.0001.100

Aren't these supposed to be invalid format for IP ?

Thanks.

**Comment by whitequark** [comment] 2017-03-31 02:19
Duplicate of https://github.com/whitequark/ipaddr.js/issues/44

**Closed by whitequark** 2017-03-31 02:19 UTC
