### ISSUE TITLE
weird bug with .isValid

### ISSUE THREAD

**Issue by EitanWeMatch** [whitequark/ipaddr.js#138] opened 2020-06-17 13:36 UTC
Hey,

i am trying to use the .isValid() function of this module and i get some weird results for my inputs.

ipaddr.isValid('31') - returns true --> should be False
basically as soon as a dot `.` is added it is parsing it correctly.

**Comment by whitequark** [comment] 2020-06-17 16:28
Duplicate of #44.

**Closed by whitequark** 2020-06-17 16:28 UTC
